### ISSUE TITLE
便利なテストツール

### ISSUE THREAD

**Issue by hatsusato** [kmc-jp/cerussite#16]
#10 のテストツールはビルドと実行が分離していて不便。
cargoにはsubcommandの機能があるようなので、そのあたりを使って便利にしたい。
https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands

**Comment by statiolake** [comment]
ビルドと実行が分離、というのは、テストツールをグローバルにインストールするかテストツールのパスを直接指定して実行する必要がある、つまりプロジェクトと完全に独立していて閉じていない、というような意味ですか？

**Comment by hatsusato** [comment]
単に、ディレクトリの下に潜ってbuildして上に上がって実行しないといけないので面倒くさいという意味です。
`cargo <なんらかのコマンド名>` をトップディレクトリで実行するだけですませたい。

**Comment by statiolake** [comment]
調べていて知ったのですが、 cargo-foo というバイナリがパスにあれば cargo foo という形で呼び出せるようですね。割と簡単に書けるのかも。今のテストツールはそのまま呼び出すと引数解析に失敗してしまいましたが...

今はテストツールを作っている段階なのでテストツールのビルドも多いですが、ある程度安定したらテストツールのビルドはバージョンアップがない限り不要になるような気がします。機能自体はそれほど大きなものではないですし...。

**Comment by statiolake** [comment]
今見てみるとシェルスクリプトも cargo-foo のような名前にして実行権限をあげておけば、 cargo foo で呼び出せるみたいです。テストツールをビルドするシェルスクリプトを cargo-build-testtool 的な名前で用意すれば cargo build-testtool でコンパイルできそうですね。

**Comment by hatsusato** [comment]
なるほど。じゃあ難しくなさそうですね。
