### ISSUE TITLE
README をまともにする

### ISSUE THREAD

**Issue by statiolake** [kmc-jp/cerussite#22]
現状、もとがテストツールの README なので cerussite-test-tool については詳しいですが、 cargo-test-cerussite はおろか cerussite 本体にすら言及していないし (これは別 PR の方がよいかと思ってあえて追記しませんでした) 、少し丁寧にしたいです。

README の cerussite の項には現在のところ cerussite がサポートしている機能などを書いてもよいのでは。

**Comment by hatsusato** [comment]
いくつか細かい話。
- `コンパイル過程の生成物` にprefixをつけるとファイルの並びが変わるのでsuffixにしたい。
- サンプルの `%` は `$` の方がいいな。端末上の例には `console` を指定するといいそうな。
    ```console
    $ cerussite-test-tool
    ```
