### ISSUE TITLE
パーサーでの Tokens の扱い

### ISSUE THREAD

**Issue by statiolake** [kmc-jp/cerussite#36]
今 Tokens は生のスライスとして扱っているので、扱いが少し面倒です。 next() や peek() などのメソッドを作りたいです。拡張トレイトで実装するか、構造体でラップするかは考え中です。

また、今のところ残りの Tokens を戻り値で返しているわけですが、これもバグを生んだり (古い tokens を使ってしまい無限ループした、など) 一貫性のない記述をしたり (ループ外に変数を用意して更新するなど) せざるを得なくなってしまうので、 &mut 参照をとって利用したいと思っています。

**Comment by hatsusato** [comment]
パーサコンビネータ的にやるとよいのかもしれない。そうじゃないかもしれない。
ちょっとやってみないとわからないな。

**Comment by statiolake** [comment]
なるほど。あまり詳しくないのですが、汎用的にパースできる部分をとり出して組み合わせるみたいなことですよね。規模が大きくなって「同じものたくさん書いてるな」みたいになってきたら考えてみようかと思います。

やってみないと分からないところはほんとにありますね。
